### ISSUE TITLE
AOT compilation error

### ISSUE THREAD

**Issue by henkensm** [TigorC/ngx-eonasdan-datetimepicker#5]
When compiling using angular-cli with ng build command we receive this error message : 
ERROR in ..../node_modules/ngx-eonasdan-datetimepicker/dist/src/sq-datetimepicker/base.d.ts (2,29): Could not find a declaration file for module 'eonasdan-bootstrap-date
timepicker'. '..../node_modules/eonasdan-bootstrap-datetimepicker/src/js/bootstrap-datetimepicker.js' implicitly has an 'any' type.

How to reproduce create a project angular-cli 
then nb build --aot

It work with the version 1.0.4

**Comment by TigorC** [comment]
Try to install `eonasdan-bootstrap-date
timepicker` types:
```bash
npm i --save-dev @types/eonasdan-bootstrap-datetimepicker@4.17.25
```
